### PR TITLE
Add BusyBox CVE submissions

### PR DESCRIPTION
**Pull request by srmish-jfrog**
Add 14 CVEs from publication - https://jfrog.com/blog/unboxing-busybox-14-new-vulnerabilities-uncovered-by-claroty-and-jfrog/

### CODE REVIEW

**Comment by cve-team** [comment]
srmish-jfrog is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

**Comment by srmish-jfrog** [comment]
Just pinging about this (I was added to the Git pilot a few days ago)

**Comment by anthnysingleton** [comment]
Hello @srmish-jfrog,

Your Json files are missing the following field. Please close this Pull Request and open a new one with the Json Files correctly formatted.

`"STATE": "RESERVED"`

Thanks,
CVE Content Team

**Comment by srmish-jfrog** [comment]
@anthnysingleton  Shouldn't it be `"STATE": "PUBLIC"` ?
Or are you responsible for changing it from `"RESERVED"` to `"PUBLIC"` ?

**Comment by anthnysingleton** [comment]
@srmish-jfrog correct you must change the field to `"STATE": "PUBLIC"`

**Pull request closed without merging**
