### PR TITLE
November 2021 Patch Tuesday

### PR DESCRIPTION
**Pull request by msrcgit**

### CODE REVIEW

**Comment by cve-team** [comment]
The git pilot currently only supports pull requests up to 300 files. Please break this pull request into multiple pull requests.

**Comment by erwanlr** [comment]
What happened here ? We got a lot of our (WPScan) published CVE reverted to a state of Reserved by this PR

For example: https://github.com/CVEProject/cvelist/commit/df296d9e014bf68ef22c0583c98da3fbe42ea316#diff-dbdd0577d2662d8b029a40123752bb4c549ced9defece555e2ffa9068c4220ad

**Comment by hagaiwech** [comment]
@cve-team @msrcgit 
Joining @erwanlr here, it seems that some of our (WhiteSource) CVE data was reverted back to a previous state.
What are those changes and why are we affected by them?

**Comment by anthnysingleton** [comment]
Hello All,

Thank you all for commenting on this Pull Request. We are aware of the issue and are working to investigate what happened and revert the changes made. 

Best,
CVE Content Team

**Comment by tibcodenny** [comment]
Thank you

**Comment by anthnysingleton** [comment]
Thank you all for your patience. I have gone through and reverted the files back to there state before this PR. Please let me know if you are seeing any lingering issues. 

Anthony

**Pull request merged**
