### PR TITLE
CERT/CC VU#590287 wget vulnerabilities from NCSC-FI

### PR DESCRIPTION
**Pull request by zmanion**

### CODE REVIEW

**Comment by cve-team** [comment]
The supplied descriptions are missing product / version info. I will add that as I populate the CVE entries, but going forward, please include it whenever possible.

**Comment by cve-team** [comment]
Thanks, Art. The entries should be published on https://cve.mitre.org within the next few hours.

George

**Comment by zmanion** [comment]
I see:
"vendor_name": "GNU Project"
"product_name": "Wget"
"version_value": "prior to 1.19.2"

**Comment by zmanion** [comment]
Oh, the Descriptions, right?

**Comment by cve-team** [comment]
Yes, I was talking about the text in the descriptions themselves. The goal is to use those to populate the entries in the CVE List.

George

**Pull request merged**
