### PR TITLE
Cna/certcc/CVE 2021 44228

### PR DESCRIPTION
**Pull request by zmanion**
Remove mitigation details which are hard to maintain and do not contribute to essential identification of the vulnerability. Add a reference, change an Apache reference to CONFIRM.

CC @iamamoose

### CODE REVIEW

**Comment by cve-team** [comment]
WARNING: Github identified an issue when verifying the signature - unknown_key

**Comment by iamamoose** [comment]
see https://github.com/CVEProject/cvelist/pull/3777

**Comment by iamamoose** [comment]
see https://github.com/CVEProject/cvelist/pull/3778

**Comment by zmanion** [comment]
This PR addressed by #3777 and #3778.

**Pull request closed without merging**
