### PR TITLE
Add PHP CVEs from April 4th release

### PR DESCRIPTION
**Pull request by smalyshev**

### CODE REVIEW

**Comment by cve-team** [comment]
smalyshev is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

**Comment by cve-team** [comment]
Hello Stanislav,

Can you please add the affected version information to the supplied descriptions?

Thanks,
CVE Assignment Team

**Comment by iamleot** [comment]
The version in the description seems to have a typo: I think that:

 `[...] 7.1.x below 7.2.8 [...]`

should be changed to:

 `[...] 7.1.x below 7.1.28 [...]`

@smalyshev can you please adjust that?

Thank you!

**Comment by smalyshev** [comment]
@iamleot fix in https://github.com/CVEProject/cvelist/pull/1926

**Comment by iamleot** [comment]
Stanislav Malyshev writes:
> @iamleot fix in https://github.com/CVEProject/cvelist/pull/1926

Thank you Stanislav!

**Pull request merged**
