### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by zmanion**
Signed-off-by: Art Manion <zmanion@protonmail.com>

### CODE REVIEW

**Comment by todb-cisa** [comment]
Hey, you should land this. Yes, you there. The one who can see the squash merge button.

**Comment by todb-cisa** [comment]
Actually, throw this out, it's already got a deprecation warning on the README.md

**Comment by todb-cisa** [comment]
Actually, throw this out, it's already got a deprecation warning on the README.md

**Comment by todb-cisa** [comment]
Actually, throw this out, it's already got a deprecation warning on the README.md

**Comment by todb-cisa** [comment]
Actually, throw this out, it's already got a deprecation warning on the README.md

**Comment by Marcono1234** [comment]
Is the information in this pull request correct, and will this repository be deprecated at the end of the year?

In that case, would it make sense to merge this pull request? Because the current warning on the README is only about the CVE Record Submission through PRs having ended, without any indication that this repository will be deprecated, or any link to the cvelistV5 repository.

**Comment by zmanion** [comment]
I think the JSON 4.0 repo will be deprecated "in the first half of 2024" along with the other older download formats. Checking on this. And yes we should add a warning about when the repo will be deprecated.

**Pull request closed without merging**
