### PR TITLE
reserved CVEs

### PR DESCRIPTION
**Pull request by kurtseifried**

### CODE REVIEW

**Comment by cve-team** [comment]
Are you planning to make more updates to the PR or can I handle it now, Kurt?

George

**Comment by cve-team** [comment]
Meh, please don't make further updates -- I'll process this shortly.

George

**Comment by kurtseifried** [comment]
sorry no, I did 2 and then had another one come in, that's the last for this batch.

**Comment by cve-team** [comment]
The three are now reserved in the CVE List.

George

**Pull request merged**
