### PR TITLE
Advisories & fixes published for Erlang LPE.

### PR DESCRIPTION
**Pull request by deepsurfacesec**
This is my first time.  Happy to hear any feedback you have on the submission.  Thanks!

### CODE REVIEW

**Comment by cve-team** [comment]
deepsurfacesec is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

**Comment by cristina479** [comment]
Could you push your changes again? For some reason our production system did picked up this PR, so I can't approve and merge it.

**Comment by deepsurfacesec** [comment]
Do I need to create a new PR?  I'm not sure how to re-push to the branch differently.

**Comment by deepsurfacesec** [comment]
BTW, did you know that the cve@mitre.org address bounces?

**Comment by cristina479** [comment]
You can use this same branch, make a small change (add a spec or a period, etc.) commit and push.

**Comment by cristina479** [comment]
Yes, we intentionally discontinued cve@mitre.org

**Comment by deepsurfacesec** [comment]
OK, give that a try.

**Pull request merged**
