### PR TITLE
PHP 7.4.31, 8.0.24, 8.1.11 security fixes

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by cve-team** [comment]
derickr is not recognized currently as an account participating in the Git Pilot. To ensure timely processing of your pull request, please contact the CVE Team using either the CVE Request web form (https://cveform.mitre.org/) or an email (cve@mitre.org) and confirm your identity.

**Comment by derickr** [comment]
The email address (cve@mitre.org) in your message above, bounces.

**Comment by smalyshev** [comment]
I'll make a pull from my ID later today, that should fix it.

**Comment by derickr** [comment]
On 27 September 2022 18:05:19 BST, Stanislav Malyshev ***@***.***> wrote:
>I'll make a pull from my ID later today, that should fix it. 
>

That's great, but it would probably be good if more than one person could do it.

cheers
Derick

**Pull request merged**
