### PR TITLE
Add CVEs for new OpenSSL vulnerabilities

### PR DESCRIPTION
**Pull request by mattcaswell**

### CODE REVIEW

**Comment by cve-team** [comment]
WARNING: Commit not verified. Reason: unknown_key

**Comment by mattcaswell** [comment]
> WARNING: Commit not verified. Reason: unknown_key

How do I correct this issue? My key details are published on the OpenSSL website:

https://www.openssl.org/community/omc.html

**Comment by mattcaswell** [comment]
And also in the OpenSSL distribution:

https://github.com/openssl/openssl/blob/master/doc/fingerprints.txt

**Comment by cve-team** [comment]
That warning Github does not know about your public key; ie, if you look at https://github.com/CVEProject/cvelist/pull/376/commits and click "Unverified", Github says "This user has not uploaded their public key yet."

**Pull request merged**
